In [1]:
import pandas as pd
import numpy as np
raw_data = pd.DataFrame({"timestamp": [1618754065+i*2000 for i in range(0, 1000)],
                         "lat":np.random.uniform(low=-90.0, high=90.0, size=(1000,)),
                         "lon": np.random.uniform(low=-180.0, high=180.0, size=(1000,)),
                         "elev": np.random.uniform(low=-100.0, high=2000.0, size=(1000,)),
                         "speed": np.random.uniform(low=0.0, high=30.0, size=(1000,))})

ModuleNotFoundError: No module named 'pandas'

In [216]:
import sqlite3
database = sqlite3.connect("../tests/unit/data/pythonsqlite.db")
raw_data = pd.read_sql_query('''SELECT * from trip_geo''', database)
database.close()

In [217]:
# Retrieve raw position
sleeping_df = raw_data
sleeping_df

       timestamp        lat         lon         elev      speed
0     1618754065 -33.204093 -150.760219  1631.646229   2.088785
1     1618756065 -79.107893  -62.129440   307.775369  13.816283
2     1618758065  44.710142 -141.177262  1909.287325  13.958821
3     1618760065   6.350283  -90.977636   733.804094  28.364322
4     1618762065  47.430304 -141.542683  1785.643948  22.756710
...          ...        ...         ...          ...        ...
1995  1622744065 -71.687189   95.857002  1040.276940  18.139910
1996  1622746065 -27.949979 -142.820312   863.053067   0.698558
1997  1622748065  79.131680 -130.286909   596.591440  25.501588
1998  1622750065  82.520297 -137.231418  1490.517607   1.234050
1999  1622752065  16.129194  -84.427973   299.158702  28.102931

[2000 rows x 5 columns]

In [218]:
# Filter the static position
static_position_threshold = 1.0
sleeping_df = sleeping_df[sleeping_df.speed <= static_position_threshold]
sleeping_df.head()

      timestamp        lat         lon         elev     speed
8    1618770065  39.510108   54.524598  1531.156560  0.846222
33   1618820065 -49.786909   -3.805875   -84.473700  0.044083
76   1618906065  70.540542 -147.444672   643.224586  0.075079
91   1618936065  37.134159  179.005622   412.721457  0.764082
120  1618994065  -9.834695  -35.758259   688.460436  0.599345

In [219]:
# Filter the last position of the day
sleeping_df['date'] = sleeping_df["timestamp"].apply(lambda x: pd.to_datetime(x, unit="s").date())
sleeping_df

c:\users\valentin.rudloff\.virtualenvs\tripoverview\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       timestamp        lat         lon         elev     speed        date
8     1618770065  39.510108   54.524598  1531.156560  0.846222  2021-04-18
33    1618820065 -49.786909   -3.805875   -84.473700  0.044083  2021-04-19
76    1618906065  70.540542 -147.444672   643.224586  0.075079  2021-04-20
91    1618936065  37.134159  179.005622   412.721457  0.764082  2021-04-20
120   1618994065  -9.834695  -35.758259   688.460436  0.599345  2021-04-21
...          ...        ...         ...          ...       ...         ...
1839  1622432065 -14.913408   42.825294   223.819450  0.479152  2021-05-31
1886  1622526065 -85.668451  150.917439   773.542181  0.039698  2021-06-01
1889  1622532065 -32.665684   85.393156  1994.683148  0.813797  2021-06-01
1915  1622584065  23.170464  -14.907387  1289.305704  0.492551  2021-06-01
1996  1622746065 -27.949979 -142.820312   863.053067  0.698558  2021-06-03

[71 rows x 6 columns]

In [220]:
sleeping_df = sleeping_df.drop_duplicates(subset=["date"], keep='last')
sleeping_df

       timestamp        lat         lon         elev     speed        date
8     1618770065  39.510108   54.524598  1531.156560  0.846222  2021-04-18
33    1618820065 -49.786909   -3.805875   -84.473700  0.044083  2021-04-19
91    1618936065  37.134159  179.005622   412.721457  0.764082  2021-04-20
120   1618994065  -9.834695  -35.758259   688.460436  0.599345  2021-04-21
173   1619100065 -17.665741   27.827906  1676.415901  0.903035  2021-04-22
223   1619200065  49.108540 -144.705454   -40.655722  0.404652  2021-04-23
252   1619258065 -59.176028  112.035235   570.679548  0.802012  2021-04-24
320   1619394065  25.913643   81.091927  1832.857968  0.936398  2021-04-25
326   1619406065  41.742930  170.609184   768.342712  0.586869  2021-04-26
395   1619544065 -75.035063   57.785614   860.170993  0.700677  2021-04-27
450   1619654065 -83.963874  108.161233   393.437186  0.325667  2021-04-28
490   1619734065  73.853564  113.165605   787.408609  0.667283  2021-04-29
496   1619746065 -30.011846 -150.484878  1549.775207  0.027021  2021-04-30
548   1619850065 -54.808218  -88.967239  1292.504801  0.948210  2021-05-01
613   1619980065  -9.762415  -14.047326  1004.967827  0.825141  2021-05-02
693   1620140065  28.191901  117.923386  1428.013416  0.597776  2021-05-04
751   1620256065 -43.179969  -28.406864   999.229044  0.117619  2021-05-05
780   1620314065 -45.809854   98.685330  1202.892600  0.384840  2021-05-06
820   1620394065  39.674107   30.809352   862.725819  0.886920  2021-05-07
879   1620512065 -68.907064  -70.422168  1674.466900  0.710473  2021-05-08
898   1620550065 -33.921022  159.840940  1010.621775  0.836585  2021-05-09
994   1620742065  78.291489 -108.948326   599.004558  0.923990  2021-05-11
1048  1620850065 -79.521303  156.818233  1450.979705  0.859797  2021-05-12
1139  1621032065  19.921294  162.477944  1686.392663  0.247947  2021-05-14
1167  1621088065  68.009408 -128.617913  1749.497719  0.032827  2021-05-15
1226  1621206065 -65.614266  152.787402  1660.814509  0.964571  2021-05-16
1259  1621272065  65.566505 -152.209710   136.547901  0.165907  2021-05-17
1293  1621340065 -41.466616   56.244597   694.814526  0.173484  2021-05-18
1357  1621468065 -43.424734   82.260052  1606.002973  0.421707  2021-05-19
1399  1621552065 -17.841950    2.194050  1837.044608  0.656916  2021-05-20
1402  1621558065 -13.477755   52.391171  1333.420571  0.242775  2021-05-21
1490  1621734065 -46.848596  -36.564925  1845.643046  0.378884  2021-05-23
1570  1621894065  10.723965 -131.715352  1248.256422  0.138847  2021-05-24
1642  1622038065 -53.790195   97.424982   380.992953  0.563906  2021-05-26
1694  1622142065  60.268767  176.480822   323.029689  0.493659  2021-05-27
1719  1622192065 -82.352387  -55.172917  1915.645595  0.132490  2021-05-28
1770  1622294065  32.176825 -124.346717    67.931604  0.127772  2021-05-29
1839  1622432065 -14.913408   42.825294   223.819450  0.479152  2021-05-31
1915  1622584065  23.170464  -14.907387  1289.305704  0.492551  2021-06-01
1996  1622746065 -27.949979 -142.820312   863.053067  0.698558  2021-06-03

In [221]:
import math
def distance(origin, destination):
    """TODO add doc"""
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371  # km

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) * math.sin(dlat / 2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon / 2) * math.sin(dlon / 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    d = radius * c

    return d

In [222]:
sleeping_df["dist_from_last"] = 0.0
print(sleeping_df["dist_from_last"].iloc[0])
sleeping_df

0.0

c:\users\valentin.rudloff\.virtualenvs\tripoverview\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,timestamp,lat,lon,elev,speed,date,dist_from_last
8,1618770065,39.510108,54.524598,1531.156560,0.846222,2021-04-18,0.0
33,1618820065,-49.786909,-3.805875,-84.473700,0.044083,2021-04-19,0.0
91,1618936065,37.134159,179.005622,412.721457,0.764082,2021-04-20,0.0
120,1618994065,-9.834695,-35.758259,688.460436,0.599345,2021-04-21,0.0
173,1619100065,-17.665741,27.827906,1676.415901,0.903035,2021-04-22,0.0
223,1619200065,49.108540,-144.705454,-40.655722,0.404652,2021-04-23,0.0
252,1619258065,-59.176028,112.035235,570.679548,0.802012,2021-04-24,0.0
320,1619394065,25.913643,81.091927,1832.857968,0.936398,2021-04-25,0.0
326,1619406065,41.742930,170.609184,768.342712,0.586869,2021-04-26,0.0
395,1619544065,-75.035063,57.785614,860.170993,0.700677,2021-04-27,0.0
450,1619654065,-83.963874,108.161233,393.437186,0.325667,2021-04-28,0.0
490,1619734065,73.853564,113.165605,787.408609,0.667283,2021-04-29,0.0
496,1619746065,-30.011846,-150.484878,1549.775207,0.027021,2021-04-30,0.0
548,1619850065,-54.808218,-88.967239,1292.504801,0.948210,2021-05-01,0.0
613,1619980065,-9.762415,-14.047326,1004.967827,0.825141,2021-05-02,0.0
693,1620140065,28.191901,117.923386,1428.013416,0.597776,2021-05-04,0.0
751,1620256065,-43.179969,-28.406864,999.229044,0.117619,2021-05-05,0.0
780,1620314065,-45.809854,98.685330,1202.892600,0.384840,2021-05-06,0.0
820,1620394065,39.674107,30.809352,862.725819,0.886920,2021-05-07,0.0
879,1620512065,-68.907064,-70.422168,1674.466900,0.710473,2021-05-08,0.0
898,1620550065,-33.921022,159.840940,1010.621775,0.836585,2021-05-09,0.0
994,1620742065,78.291489,-108.948326,599.004558,0.923990,2021-05-11,0.0
1048,1620850065,-79.521303,156.818233,1450.979705,0.859797,2021-05-12,0.0
1139,1621032065,19.921294,162.477944,1686.392663,0.247947,2021-05-14,0.0
1167,1621088065,68.009408,-128.617913,1749.497719,0.032827,2021-05-15,0.0
1226,1621206065,-65.614266,152.787402,1660.814509,0.964571,2021-05-16,0.0
1259,1621272065,65.566505,-152.209710,136.547901,0.165907,2021-05-17,0.0
1293,1621340065,-41.466616,56.244597,694.814526,0.173484,2021-05-18,0.0
1357,1621468065,-43.424734,82.260052,1606.002973,0.421707,2021-05-19,0.0
1399,1621552065,-17.841950,2.194050,1837.044608,0.656916,2021-05-20,0.0
1402,1621558065,-13.477755,52.391171,1333.420571,0.242775,2021-05-21,0.0
1490,1621734065,-46.848596,-36.564925,1845.643046,0.378884,2021-05-23,0.0
1570,1621894065,10.723965,-131.715352,1248.256422,0.138847,2021-05-24,0.0
1642,1622038065,-53.790195,97.424982,380.992953,0.563906,2021-05-26,0.0
1694,1622142065,60.268767,176.480822,323.029689,0.493659,2021-05-27,0.0
1719,1622192065,-82.352387,-55.172917,1915.645595,0.132490,2021-05-28,0.0
1770,1622294065,32.176825,-124.346717,67.931604,0.127772,2021-05-29,0.0
1839,1622432065,-14.913408,42.825294,223.819450,0.479152,2021-05-31,0.0
1915,1622584065,23.170464,-14.907387,1289.305704,0.492551,2021-06-01,0.0
1996,1622746065,-27.949979,-142.820312,863.053067,0.698558,2021-06-03,0.0

In [223]:
sleeping_df["dist_from_last"] = 0.0
for i in range(1, len(sleeping_df[["lat", "lon"]])):
    sleeping_df["dist_from_last"].iloc[i] = distance(sleeping_df[["lat", "lon"]].iloc[i-1].values,
                                                     sleeping_df[["lat", "lon"]].iloc[i].values)
sleeping_df

c:\users\valentin.rudloff\.virtualenvs\tripoverview\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\users\valentin.rudloff\.virtualenvs\tripoverview\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\users\valentin.rudloff\.virtualenvs\tripoverview\lib\site-packages\pandas\core\indexing.py:692: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

,timestamp,lat,lon,elev,speed,date,dist_from_last
8,1618770065,39.510108,54.524598,1531.156560,0.846222,2021-04-18,0.000000
33,1618820065,-49.786909,-3.805875,-84.473700,0.044083,2021-04-19,11448.985661
91,1618936065,37.134159,179.005622,412.721457,0.764082,2021-04-20,18590.257082
120,1618994065,-9.834695,-35.758259,688.460436,0.599345,2021-04-21,15395.302240
173,1619100065,-17.665741,27.827906,1676.415901,0.903035,2021-04-22,6894.038395
223,1619200065,49.108540,-144.705454,-40.655722,0.404652,2021-04-23,16454.736636
252,1619258065,-59.176028,112.035235,570.679548,0.802012,2021-04-24,15184.864657
320,1619394065,25.913643,81.091927,1832.857968,0.936398,2021-04-25,9880.100962
326,1619406065,41.742930,170.609184,768.342712,0.586869,2021-04-26,8088.940405
395,1619544065,-75.035063,57.785614,860.170993,0.700677,2021-04-27,15109.739729
450,1619654065,-83.963874,108.161233,393.437186,0.325667,2021-04-28,1337.466428
490,1619734065,73.853564,113.165605,787.408609,0.667283,2021-04-29,17550.380074
496,1619746065,-30.011846,-150.484878,1549.775207,0.027021,2021-04-30,13395.604882
548,1619850065,-54.808218,-88.967239,1292.504801,0.948210,2021-05-01,5526.734768
613,1619980065,-9.762415,-14.047326,1004.967827,0.825141,2021-05-02,8157.377222
693,1620140065,28.191901,117.923386,1428.013416,0.597776,2021-05-04,14608.261481
751,1620256065,-43.179969,-28.406864,999.229044,0.117619,2021-05-05,16580.398715
780,1620314065,-45.809854,98.685330,1202.892600,0.384840,2021-05-06,8827.848713
820,1620394065,39.674107,30.809352,862.725819,0.886920,2021-05-07,11654.983652
879,1620512065,-68.907064,-70.422168,1674.466900,0.710473,2021-05-08,14512.180349
898,1620550065,-33.921022,159.840940,1010.621775,0.836585,2021-05-09,7866.611464
994,1620742065,78.291489,-108.948326,599.004558,0.923990,2021-05-11,13717.757203
1048,1620850065,-79.521303,156.818233,1450.979705,0.859797,2021-05-12,18338.837688
1139,1621032065,19.921294,162.477944,1686.392663,0.247947,2021-05-14,11062.896016
1167,1621088065,68.009408,-128.617913,1749.497719,0.032827,2021-05-15,7086.098171
1226,1621206065,-65.614266,152.787402,1660.814509,0.964571,2021-05-16,16065.850184
1259,1621272065,65.566505,-152.209710,136.547901,0.165907,2021-05-17,15232.915255
1293,1621340065,-41.466616,56.244597,694.814526,0.173484,2021-05-18,16800.591576
1357,1621468065,-43.424734,82.260052,1606.002973,0.421707,2021-05-19,2136.956849
1399,1621552065,-17.841950,2.194050,1837.044608,0.656916,2021-05-20,7865.754016
1402,1621558065,-13.477755,52.391171,1333.420571,0.242775,2021-05-21,5381.297128
1490,1621734065,-46.848596,-36.564925,1845.643046,0.378884,2021-05-23,8840.541530
1570,1621894065,10.723965,-131.715352,1248.256422,0.138847,2021-05-24,11264.898209
1642,1622038065,-53.790195,97.424982,380.992953,0.563906,2021-05-26,13565.323600
1694,1622142065,60.268767,176.480822,323.029689,0.493659,2021-05-27,14473.967524
1719,1622192065,-82.352387,-55.172917,1915.645595,0.132490,2021-05-28,17164.832671
1770,1622294065,32.176825,-124.346717,67.931604,0.127772,2021-05-29,13253.633444
1839,1622432065,-14.913408,42.825294,223.819450,0.479152,2021-05-31,17697.050980
1915,1622584065,23.170464,-14.907387,1289.305704,0.492551,2021-06-01,7572.205956
1996,1622746065,-27.949979,-142.820312,863.053067,0.698558,2021-06-03,14801.379365

In [224]:
sleeping_df = sleeping_df[sleeping_df.dist_from_last >= 10000]
sleeping_df

,timestamp,lat,lon,elev,speed,date,dist_from_last
33,1618820065,-49.786909,-3.805875,-84.473700,0.044083,2021-04-19,11448.985661
91,1618936065,37.134159,179.005622,412.721457,0.764082,2021-04-20,18590.257082
120,1618994065,-9.834695,-35.758259,688.460436,0.599345,2021-04-21,15395.302240
223,1619200065,49.108540,-144.705454,-40.655722,0.404652,2021-04-23,16454.736636
252,1619258065,-59.176028,112.035235,570.679548,0.802012,2021-04-24,15184.864657
395,1619544065,-75.035063,57.785614,860.170993,0.700677,2021-04-27,15109.739729
490,1619734065,73.853564,113.165605,787.408609,0.667283,2021-04-29,17550.380074
496,1619746065,-30.011846,-150.484878,1549.775207,0.027021,2021-04-30,13395.604882
693,1620140065,28.191901,117.923386,1428.013416,0.597776,2021-05-04,14608.261481
751,1620256065,-43.179969,-28.406864,999.229044,0.117619,2021-05-05,16580.398715
820,1620394065,39.674107,30.809352,862.725819,0.886920,2021-05-07,11654.983652
879,1620512065,-68.907064,-70.422168,1674.466900,0.710473,2021-05-08,14512.180349
994,1620742065,78.291489,-108.948326,599.004558,0.923990,2021-05-11,13717.757203
1048,1620850065,-79.521303,156.818233,1450.979705,0.859797,2021-05-12,18338.837688
1139,1621032065,19.921294,162.477944,1686.392663,0.247947,2021-05-14,11062.896016
1226,1621206065,-65.614266,152.787402,1660.814509,0.964571,2021-05-16,16065.850184
1259,1621272065,65.566505,-152.209710,136.547901,0.165907,2021-05-17,15232.915255
1293,1621340065,-41.466616,56.244597,694.814526,0.173484,2021-05-18,16800.591576
1570,1621894065,10.723965,-131.715352,1248.256422,0.138847,2021-05-24,11264.898209
1642,1622038065,-53.790195,97.424982,380.992953,0.563906,2021-05-26,13565.323600
1694,1622142065,60.268767,176.480822,323.029689,0.493659,2021-05-27,14473.967524
1719,1622192065,-82.352387,-55.172917,1915.645595,0.132490,2021-05-28,17164.832671
1770,1622294065,32.176825,-124.346717,67.931604,0.127772,2021-05-29,13253.633444
1839,1622432065,-14.913408,42.825294,223.819450,0.479152,2021-05-31,17697.050980
1996,1622746065,-27.949979,-142.820312,863.053067,0.698558,2021-06-03,14801.379365

In [228]:
sleeping_df[["timestamp", "lat", "lon", "elev"]].values.tolist()

[[1618820065.0, -49.78690939348198, -3.805875048742564, -84.47370043631621],
 [1618936065.0, 37.13415931996609, 179.00562167415478, 412.7214569389232],
 [1618994065.0, -9.83469485563809, -35.75825919803481, 688.4604363848367],
 [1619200065.0, 49.10854041902809, -144.70545444081387, -40.65572220233265],
 [1619258065.0, -59.176027937074196, 112.0352349203165, 570.6795476207768],
 [1619544065.0, -75.03506256640486, 57.78561399733644, 860.1709928073229],
 [1619734065.0, 73.85356360901267, 113.16560472344452, 787.4086088312232],
 [1619746065.0, -30.011845773073645, -150.48487842130208, 1549.7752073372694],
 [1620140065.0, 28.19190068663478, 117.92338615287599, 1428.013416142928],
 [1620256065.0, -43.17996948492938, -28.40686355209135, 999.2290435846639],
 [1620394065.0, 39.67410695295811, 30.809351967524776, 862.7258185399526],
 [1620512065.0, -68.90706422529061, -70.42216768231695, 1674.466900226373],
 [1620742065.0, 78.29148861767439, -108.94832646361277, 599.0045583237422],
 [1620850065.0, -79.52130256523658, 156.81823342705684, 1450.9797053383274],
 [1621032065.0, 19.921294159216274, 162.47794400338074, 1686.3926625304277],
 [1621206065.0, -65.61426592379706, 152.7874024853577, 1660.814508914641],
 [1621272065.0, 65.56650534378679, -152.20970971831383, 136.54790141266858],
 [1621340065.0, -41.466615989799635, 56.24459724742093, 694.8145263082174],
 [1621894065.0, 10.723964812681018, -131.71535211282134, 1248.2564223310246],
 [1622038065.0, -53.79019529092054, 97.42498161064202, 380.9929525750793],
 [1622142065.0, 60.268767375171564, 176.48082179931674, 323.0296889952723],
 [1622192065.0, -82.35238665518891, -55.17291712220019, 1915.6455951554658],
 [1622294065.0, 32.17682481821515, -124.3467174563323, 67.93160418836774],
 [1622432065.0, -14.91340773935437, 42.82529433417446, 223.81945003652766],
 [1622746065.0, -27.949979158501407, -142.8203118402694, 863.0530667251164]]

In [235]:
import os
import sys
os.path.join(os.getcwd(), "data", "test.db")

'D:\\sources\\perso\\TripOverview\\prototype\\data\\test.db'